/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Entero = 5;
  /** RegularExpression Id. */
  int Flotante = 6;
  /** RegularExpression Id. */
  int Boleano = 7;
  /** RegularExpression Id. */
  int Char = 8;
  /** RegularExpression Id. */
  int String = 9;
  /** RegularExpression Id. */
  int operadorSuma = 10;
  /** RegularExpression Id. */
  int operadorResta = 11;
  /** RegularExpression Id. */
  int operadorMultiplicacion = 12;
  /** RegularExpression Id. */
  int operadorDiviSion = 13;
  /** RegularExpression Id. */
  int operadorModulo = 14;
  /** RegularExpression Id. */
  int operadorAsignacion = 15;
  /** RegularExpression Id. */
  int operadorAND = 16;
  /** RegularExpression Id. */
  int operadorOR = 17;
  /** RegularExpression Id. */
  int operadorNOT = 18;
  /** RegularExpression Id. */
  int operadorMenoroIgual = 19;
  /** RegularExpression Id. */
  int operadorMayoroIgual = 20;
  /** RegularExpression Id. */
  int operadorIgualdad = 21;
  /** RegularExpression Id. */
  int operadorMenorQue = 22;
  /** RegularExpression Id. */
  int operadorMayorQue = 23;
  /** RegularExpression Id. */
  int operadorIncremento = 24;
  /** RegularExpression Id. */
  int operadorDecremento = 25;
  /** RegularExpression Id. */
  int condicionalIF = 26;
  /** RegularExpression Id. */
  int condicionalElSE = 27;
  /** RegularExpression Id. */
  int condicionalSWITCH = 28;
  /** RegularExpression Id. */
  int caseSwitch = 29;
  /** RegularExpression Id. */
  int puntoyComa = 30;
  /** RegularExpression Id. */
  int dosPuntos = 31;
  /** RegularExpression Id. */
  int parentesisAbre = 32;
  /** RegularExpression Id. */
  int parentesisCierra = 33;
  /** RegularExpression Id. */
  int llaveAbre = 34;
  /** RegularExpression Id. */
  int llaveCierra = 35;
  /** RegularExpression Id. */
  int corcheteAbre = 36;
  /** RegularExpression Id. */
  int corcheteCierra = 37;
  /** RegularExpression Id. */
  int Incicio = 38;
  /** RegularExpression Id. */
  int Final = 39;
  /** RegularExpression Id. */
  int declaracionVariable = 40;
  /** RegularExpression Id. */
  int declaracionFuncion = 41;
  /** RegularExpression Id. */
  int salidaEstandar = 42;
  /** RegularExpression Id. */
  int entradaEstandar = 43;
  /** RegularExpression Id. */
  int comentario = 44;
  /** RegularExpression Id. */
  int comentarioMultipleAbre = 45;
  /** RegularExpression Id. */
  int comentarioMultipleCierra = 46;
  /** RegularExpression Id. */
  int numeroEntero = 47;
  /** RegularExpression Id. */
  int numeroFlotante = 48;
  /** RegularExpression Id. */
  int identificador = 49;
  /** RegularExpression Id. */
  int cadenadeCaracteres = 50;
  /** RegularExpression Id. */
  int CARACTER_ILEGAL = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"char\"",
    "\"string\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"++\"",
    "\"--\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"_inicio\"",
    "\"final_\"",
    "\"coco\"",
    "\"fn\"",
    "\"print!\"",
    "\"scan!\"",
    "\"//\"",
    "\"/#\"",
    "\"#/\"",
    "<numeroEntero>",
    "<numeroFlotante>",
    "<identificador>",
    "<cadenadeCaracteres>",
    "<CARACTER_ILEGAL>",
  };

}
