/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_UNILINEA = 5;
  /** RegularExpression Id. */
  int ENTERO = 6;
  /** RegularExpression Id. */
  int FLOTANTE = 7;
  /** RegularExpression Id. */
  int BOOLEANO = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int OPERADOR_MENOR_O_IGUAL = 11;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR_O_IGUAL = 12;
  /** RegularExpression Id. */
  int OPERADOR_IGUALDAD = 13;
  /** RegularExpression Id. */
  int OPERADOR_DESIGUALDAD = 14;
  /** RegularExpression Id. */
  int OPERADOR_MENOR_QUE = 15;
  /** RegularExpression Id. */
  int OPERADOR_MAYOR_QUE = 16;
  /** RegularExpression Id. */
  int OPERADOR_INCREMENTO = 17;
  /** RegularExpression Id. */
  int OPERADOR_DECREMENTO = 18;
  /** RegularExpression Id. */
  int OPERADOR_SUMA = 19;
  /** RegularExpression Id. */
  int OPERADOR_RESTA = 20;
  /** RegularExpression Id. */
  int OPERADOR_MULTIPLICACION = 21;
  /** RegularExpression Id. */
  int OPERADOR_DIVISION = 22;
  /** RegularExpression Id. */
  int OPERADOR_MODULO = 23;
  /** RegularExpression Id. */
  int OPERADOR_ASIGNACION = 24;
  /** RegularExpression Id. */
  int OPERADOR_AND = 25;
  /** RegularExpression Id. */
  int OPERADOR_OR = 26;
  /** RegularExpression Id. */
  int OPERADOR_NOT = 27;
  /** RegularExpression Id. */
  int CONDICIONAL_IF = 28;
  /** RegularExpression Id. */
  int CONDICIONAL_ELSE = 29;
  /** RegularExpression Id. */
  int CONDICIONAL_SWITCH = 30;
  /** RegularExpression Id. */
  int CASE_CONDICIONAL_SWITCH = 31;
  /** RegularExpression Id. */
  int BLUCLE_FOR = 32;
  /** RegularExpression Id. */
  int BUCLE_WHILE = 33;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 34;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 35;
  /** RegularExpression Id. */
  int PARENTSIS_ABRE = 36;
  /** RegularExpression Id. */
  int PARENTESIS_CIERRA = 37;
  /** RegularExpression Id. */
  int LLAVE_ABRE = 38;
  /** RegularExpression Id. */
  int LLAVE_CIERRA = 39;
  /** RegularExpression Id. */
  int CORCHETE_ABRE = 40;
  /** RegularExpression Id. */
  int CORCHETE_CIERRA = 41;
  /** RegularExpression Id. */
  int INICIO = 42;
  /** RegularExpression Id. */
  int FINAL = 43;
  /** RegularExpression Id. */
  int INICIO_DECLARACION_VARIABLE = 44;
  /** RegularExpression Id. */
  int INICIO_DECLARACION_FUNCION = 45;
  /** RegularExpression Id. */
  int SALIDA = 46;
  /** RegularExpression Id. */
  int ENTRADA = 47;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 48;
  /** RegularExpression Id. */
  int NUMERO_FLOTANTE = 49;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 50;
  /** RegularExpression Id. */
  int CADENA_DE_CARACTERES = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO_UNILINEA>",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"char\"",
    "\"string\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"for\"",
    "\"while\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"_inicio\"",
    "\"final_\"",
    "\"coco\"",
    "\"fn\"",
    "\"print!\"",
    "\"scan!\"",
    "<NUMERO_ENTERO>",
    "<NUMERO_FLOTANTE>",
    "<IDENTIFICADOR>",
    "<CADENA_DE_CARACTERES>",
  };

}
