/* Gramatica.java */
/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
package parser;
import static coco.colores.*;
import coco.entrada;
import static java.lang.System.out;

import java.io.InputStream;

import static java.lang.System.err;


public class Gramatica implements GramaticaConstants {
  public static void main(String args []) throws ParseException
  {
          if (args.length == 0)
          {
                  err.println("ERROR: Se requiere la ruta del archivo fuente..." + "\n");
                  return;
          }

          String rutaArchivo = args[0];

          try (InputStream is = entrada.leerCodigoFuente(rutaArchivo))
          {
                  Gramatica parser = new Gramatica(is);
                  parser.Coco();
          }
          catch (java.io.IOException e)
          {
            err.println("Error al leer el archivo" + e.getMessage());
          }
  }

  static final public void Coco() throws ParseException {
    jj_consume_token(INICIO);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INICIO_DECLARACION_VARIABLE:
      case SALIDA:
      case ENTRADA:
      case NUMERO_ENTERO:
      case NUMERO_FLOTANTE:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      sentancias();
    }
    jj_consume_token(FINAL);
    jj_consume_token(0);
}

  static final public void sentancias() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INICIO_DECLARACION_VARIABLE:{
      declaracionDeVariables();
      break;
      }
    case ENTRADA:{
      entrada();
      break;
      }
    case SALIDA:{
      salida();
      break;
      }
    case NUMERO_ENTERO:
    case NUMERO_FLOTANTE:
    case IDENTIFICADOR:{
      operacionDeComparacion();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void declaracionDeVariables() throws ParseException {
    jj_consume_token(INICIO_DECLARACION_VARIABLE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:{
      jj_consume_token(ENTERO);
      break;
      }
    case FLOTANTE:{
      jj_consume_token(FLOTANTE);
      break;
      }
    case BOOLEANO:{
      jj_consume_token(BOOLEANO);
      break;
      }
    case CHAR:{
      jj_consume_token(CHAR);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(DOS_PUNTOS);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(OPERADOR_ASIGNACION);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_ENTERO:{
      jj_consume_token(NUMERO_ENTERO);
      break;
      }
    case NUMERO_FLOTANTE:{
      jj_consume_token(NUMERO_FLOTANTE);
      break;
      }
    case CADENA_DE_CARACTERES:{
      jj_consume_token(CADENA_DE_CARACTERES);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTO_Y_COMA);
}

/*void asignacionDeValores() :
{}
{
  ( < IDENTIFICADOR > < OPERADOR_ASIGNACION > < IDENTIFICADOR > < PUNTO_Y_COMA > )
}*/
  static final public 
void entrada() throws ParseException {
    jj_consume_token(ENTRADA);
    jj_consume_token(PARENTSIS_ABRE);
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(PARENTESIS_CIERRA);
    jj_consume_token(PUNTO_Y_COMA);
}

  static final public void salida() throws ParseException {
    jj_consume_token(SALIDA);
    jj_consume_token(PARENTSIS_ABRE);
    jj_consume_token(CADENA_DE_CARACTERES);
    jj_consume_token(PARENTESIS_CIERRA);
    jj_consume_token(PUNTO_Y_COMA);
}

  static final public void operacionDeComparacion() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case NUMERO_ENTERO:{
      jj_consume_token(NUMERO_ENTERO);
      break;
      }
    case NUMERO_FLOTANTE:{
      jj_consume_token(NUMERO_FLOTANTE);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_MENOR_O_IGUAL:{
      jj_consume_token(OPERADOR_MENOR_O_IGUAL);
      break;
      }
    case OPERADOR_MAYOR_O_IGUAL:{
      jj_consume_token(OPERADOR_MAYOR_O_IGUAL);
      break;
      }
    case OPERADOR_MENOR_QUE:{
      jj_consume_token(OPERADOR_MENOR_QUE);
      break;
      }
    case OPERADOR_MAYOR_QUE:{
      jj_consume_token(OPERADOR_MAYOR_QUE);
      break;
      }
    case OPERADOR_IGUALDAD:{
      jj_consume_token(OPERADOR_IGUALDAD);
      break;
      }
    case OPERADOR_DESIGUALDAD:{
      jj_consume_token(OPERADOR_DESIGUALDAD);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case NUMERO_ENTERO:{
      jj_consume_token(NUMERO_ENTERO);
      break;
      }
    case NUMERO_FLOTANTE:{
      jj_consume_token(NUMERO_FLOTANTE);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTO_Y_COMA);
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public GramaticaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[7];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x0,0x7c0,0x0,0x0,0x1f800,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x7d000,0x7d000,0x0,0xf0000,0x70000,0x0,0x70000,};
	}

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GramaticaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 7; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[52];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 7; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 52; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
