/* Gramatica.java */
/* Generated By:JavaCC: Do not edit this line. Gramatica.java */
package parser;
import static coco.colores.*;
import coco.entrada;
import static java.lang.System.out;
import java.io.IOException;
import coco.Tabla;
import coco.Simbolo;
import arbol.Arbol;

import java.io.InputStream;

import static java.lang.System.err;


public class Gramatica implements GramaticaConstants {

                private static Tabla tabla = new Tabla();

                public static Tabla getTabla()
                {
                        return tabla;
                }

  public static void main(String args []) throws ParseException, IOException
  {
          if (args.length == 0)
          {
                  err.println("ERROR: Se requiere la ruta del archivo fuente...");
                  //return;
                  System.exit(1);
          }

          String rutaArchivo = args[0];

          InputStream is = entrada.leerCodigoFuente(rutaArchivo);
          Gramatica parser = new Gramatica(is);
          parser.Coco();
          is.close();

  }

// Producción principal.
  static final public Arbol Coco() throws ParseException {Arbol raiz = new Arbol("Arbol del archivo analizado:");
        Arbol fn, stmt;
        Token t_inicio, t_final;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INICIO_DECLARACION_FUNCION:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      fn = funcion();
raiz.agregarHijo(fn);
    }
    t_inicio = jj_consume_token(INICIO);
raiz.agregarHijo(new Arbol("Token: " + t_inicio.image));
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case CONDICIONAL_IF:
      case CONDICIONAL_SWITCH:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case INICIO_DECLARACION_VARIABLE:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      stmt = sentencia();
raiz.agregarHijo(stmt);
    }
    t_final = jj_consume_token(FINAL);
raiz.agregarHijo(new Arbol("Token: " + t_final.image));
    jj_consume_token(0);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
}

// Funciones, van antes de la funcion principal (< INICIO > *** < FINAL >)
// Si regresa un valor, debe ser especificado explicitamente,
// declarando el tipo y el nombre de la variable
  static final public Arbol funcion() throws ParseException {Arbol nodoFuncion = new Arbol("DeclaracionDeFuncion");
        String tipoRetorno, nombreFuncion;
        Arbol parametros, bloque;
        Token t_decl, t_id, t_flecha, t_pa, t_pc;
    t_decl = jj_consume_token(INICIO_DECLARACION_FUNCION);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_decl.image));
    t_id = jj_consume_token(IDENTIFICADOR);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_id.image));
                nombreFuncion = t_id.image;
    t_flecha = jj_consume_token(FLECHA);
nodoFuncion.agregarHijo(new Arbol ("Token " + t_flecha.image));
    tipoRetorno = tiposDeDatos();
nodoFuncion.agregarHijo(new Arbol("TipoRetorno: " + tipoRetorno));
Simbolo simboloFuncion = new Simbolo(nombreFuncion, "funcion", tabla.getAmbitoActual(), t_id.beginLine);
          //simboloFuncion.tipoRetorno = tipoRetorno;
      tabla.insertar(simboloFuncion);
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoFuncion.agregarHijo(new Arbol ("Token " + t_pa.image));
tabla.entrarAmbito(nombreFuncion);
    parametros = listaParametros();
nodoFuncion.agregarHijo(parametros);
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoFuncion.agregarHijo(new Arbol ("Token " + t_pc.image));
    //{ tabla.entrarAmbito(nombreFuncion); }
    
            bloque = bloqueDeCodigo();
nodoFuncion.agregarHijo(bloque);
tabla.salirAmbito();
{if ("" != null) return nodoFuncion;}
    throw new Error("Missing return statement in function");
}

// Lista de parametros que se pueden pasar a una función. (Producción)
  static final public Arbol listaParametros() throws ParseException {Arbol nodoListaDeParametros = new Arbol("ListaDeParametros");
        Arbol param;
        Token t_coma;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:
    case FLOTANTE:
    case BOOLEANO:
    case CHAR:
    case STRING:{
      param = parametro();
nodoListaDeParametros.agregarHijo(param);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        t_coma = jj_consume_token(COMA);
nodoListaDeParametros.agregarHijo(new Arbol ("Token: " + t_coma.image));
        param = parametro();
nodoListaDeParametros.agregarHijo(param);
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
{if ("" != null) return nodoListaDeParametros;}
    throw new Error("Missing return statement in function");
}

// Regla que define los parametros individuales.
  static final public Arbol parametro() throws ParseException {Arbol nodoParametro = new Arbol("ParametroIndividual");
        Token t_dos_puntos, t_id;
        String tipoDato;
    tipoDato = tiposDeDatos();
nodoParametro.agregarHijo(new Arbol("Tipo: " + tipoDato));
    t_dos_puntos = jj_consume_token(DOS_PUNTOS);
nodoParametro.agregarHijo(new Arbol ("Token: " + t_dos_puntos.image));
    t_id = jj_consume_token(IDENTIFICADOR);
nodoParametro.agregarHijo(new Arbol ("Token: " + t_id.image));

                Simbolo nuevoParametro = new Simbolo(t_id.image, tipoDato, tabla.getAmbitoActual(), t_id.beginLine);

                tabla.insertar(nuevoParametro);
{if ("" != null) return nodoParametro;}
    throw new Error("Missing return statement in function");
}

// Es lo que esta dentro de llaves
// - > Su "scope" debe ser 1.
  static final public Arbol bloqueDeCodigo() throws ParseException {Arbol nodoBloque = new Arbol("BloqueDeCodigo");
        Arbol sentencia;
        Token t_llave_a, t_llave_c;
    t_llave_a = jj_consume_token(LLAVE_ABRE);
nodoBloque.agregarHijo(new Arbol ("Token: " + t_llave_a.image));
                tabla.entrarAmbito("bloque_" + t_llave_a.beginLine);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case CONDICIONAL_IF:
      case CONDICIONAL_SWITCH:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case INICIO_DECLARACION_VARIABLE:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      sentencia = sentencia();
nodoBloque.agregarHijo(sentencia);
    }
    t_llave_c = jj_consume_token(LLAVE_CIERRA);
nodoBloque.agregarHijo(new Arbol ("Token: " + t_llave_c.image));
                tabla.salirAmbito();
{if ("" != null) return nodoBloque;}
    throw new Error("Missing return statement in function");
}

// Producción sentencia
  static final public Arbol sentencia() throws ParseException {Arbol s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INICIO_DECLARACION_VARIABLE:{
      s = declaracionDeVariable();
{if ("" != null) return s;}
      break;
      }
    case ENTERO:
    case FLOTANTE:
    case BOOLEANO:
    case CHAR:
    case STRING:{
      s = declaracionVector();
{if ("" != null) return s;}
      break;
      }
    case SALIDA:{
      s = salida();
{if ("" != null) return s;}
      break;
      }
    case ENTRADA:{
      s = entrada();
{if ("" != null) return s;}
      break;
      }
    case BUCLE_FOR:{
      s = bucleFor();
{if ("" != null) return s;}
      break;
      }
    case BUCLE_WHILE:{
      s = bucleWhile();
{if ("" != null) return s;}
      break;
      }
    case CONDICIONAL_IF:{
      s = condicionalIf();
{if ("" != null) return s;}
      break;
      }
    case CONDICIONAL_SWITCH:{
      s = condicionalSwitch();
{if ("" != null) return s;}
      break;
      }
    case RETURN:{
      s = sentenciaRetorno();
{if ("" != null) return s;}
      break;
      }
    case IDENTIFICADOR:{
      s = sentenciasConIdentificador();
{if ("" != null) return s;}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Arbol sentenciasConIdentificador() throws ParseException {Arbol nodo = new Arbol("SentenciasConIdentificador");
        Arbol llamadaFunc, accVector, exp;
        Token t_pc, t_asig, t_id;
    if (jj_2_1(3)) {
      llamadaFunc = llamadaFuncion();
nodo.agregarHijo(llamadaFunc);
      t_pc = jj_consume_token(PUNTO_Y_COMA);
nodo.agregarHijo(new Arbol ("Token: " + t_pc.image));
{if ("" != null) return nodo;}
    } else if (jj_2_2(3)) {
      accVector = accesoVector();
nodo.agregarHijo(accVector);
      t_asig = jj_consume_token(OPERADOR_ASIGNACION);
nodo.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
nodo.agregarHijo(exp);
      t_pc = jj_consume_token(PUNTO_Y_COMA);
nodo.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodo;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFICADOR:{
        t_id = jj_consume_token(IDENTIFICADOR);
nodo.agregarHijo(new Arbol("ID_Asignacion: " + t_id.image));

                        Simbolo simboloUsado = tabla.buscar(t_id.image);

                 if (simboloUsado == null)
                 {
                System.err.println("Error ??? L\u00ednea: " + t_id.beginLine + " La variable '" + t_id.image
                + "' no ha sido declarada.");
                 }
        t_asig = jj_consume_token(OPERADOR_ASIGNACION);
nodo.agregarHijo(new Arbol("Token: " + t_asig.image));
        exp = expresion();
nodo.agregarHijo(exp);
        t_pc = jj_consume_token(PUNTO_Y_COMA);
nodo.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodo;}
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Arbol sentenciaRetorno() throws ParseException {Arbol nodoRetorno = new Arbol("SentenciaDeRetorno");
        Arbol exp;
        Token t_return, t_pc;
    t_return = jj_consume_token(RETURN);
nodoRetorno.agregarHijo(new Arbol ("Token: " + t_return.image));
    exp = expresion();
nodoRetorno.agregarHijo(exp);
    t_pc = jj_consume_token(PUNTO_Y_COMA);
nodoRetorno.agregarHijo(new Arbol ("Token: " + t_pc.image));
{if ("" != null) return nodoRetorno;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol llamadaFuncion() throws ParseException {Arbol nodoLlamadaFuncion = new Arbol("LlamadaAFuncion");
        Arbol exp;
        Token t_id, t_pa, t_pc, t_coma;
    t_id = jj_consume_token(IDENTIFICADOR);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_id.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_pa.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_RESTA:
    case OPERADOR_INCREMENTO:
    case OPERADOR_DECREMENTO:
    case OPERADOR_NOT:
    case PARENTESIS_ABRE:
    case NUMERO_FLOTANTE:
    case NUMERO_ENTERO:
    case IDENTIFICADOR:
    case CADENA_DE_CARACTERES:{
      exp = expresion();
nodoLlamadaFuncion.agregarHijo(exp);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_5;
        }
        t_coma = jj_consume_token(COMA);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_coma.image));
        exp = expresion();
nodoLlamadaFuncion.agregarHijo(exp);
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_pc.image));
{if ("" != null) return nodoLlamadaFuncion;}
    throw new Error("Missing return statement in function");
}

// *** Expresiones usando precedencia ***

// Expresiones (+, -, ||)
  static final public Arbol expresion() throws ParseException {Arbol izquierda, derecha;
        Token op;
    // Primer operando siempre es mas fuerte, por lo que va a la izquierda.
            izquierda = expresionRelacional();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_SUMA:
      case OPERADOR_RESTA:
      case OPERADOR_OR:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_SUMA:{
        op = jj_consume_token(OPERADOR_SUMA);
        break;
        }
      case OPERADOR_RESTA:{
        op = jj_consume_token(OPERADOR_RESTA);
        break;
        }
      case OPERADOR_OR:{
        op = jj_consume_token(OPERADOR_OR);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      derecha = expresionRelacional();
// Nodo para las operaciones.
                // Nuevo padre.
                Arbol nodoOperacion = new Arbol("Operacion_SUM_RES_OR: " + op.image);

                        //sub-árbol anterior (el de la izquierda) como el primer hijo.
                nodoOperacion.agregarHijo(izquierda);

                //Operador
                        nodoOperacion.agregarHijo(new Arbol("Token: " + op.image));

                        // Operando de la derecha
                        nodoOperacion.agregarHijo(derecha);

                        // Actualizamos izquierda, porque puede iterar muchas veces
                        izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// relacionales (==, !=, <, >, <=, >=)
  static final public Arbol expresionRelacional() throws ParseException {Arbol izquierda, derecha;
        Token op;
    // Primer termino
            izquierda = termino();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_MENOR_O_IGUAL:
      case OPERADOR_MAYOR_O_IGUAL:
      case OPERADOR_IGUALDAD:
      case OPERADOR_DESIGUALDAD:
      case OPERADOR_MENOR_QUE:
      case OPERADOR_MAYOR_QUE:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_IGUALDAD:{
        op = jj_consume_token(OPERADOR_IGUALDAD);
        break;
        }
      case OPERADOR_DESIGUALDAD:{
        op = jj_consume_token(OPERADOR_DESIGUALDAD);
        break;
        }
      case OPERADOR_MENOR_QUE:{
        op = jj_consume_token(OPERADOR_MENOR_QUE);
        break;
        }
      case OPERADOR_MAYOR_QUE:{
        op = jj_consume_token(OPERADOR_MAYOR_QUE);
        break;
        }
      case OPERADOR_MENOR_O_IGUAL:{
        op = jj_consume_token(OPERADOR_MENOR_O_IGUAL);
        break;
        }
      case OPERADOR_MAYOR_O_IGUAL:{
        op = jj_consume_token(OPERADOR_MAYOR_O_IGUAL);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      // Segundo termino (derecha);
              derecha = termino();
// Nuevo nodo padre (operacion).
                Arbol nodoOperacion = new Arbol("Operador_Relacional" +  op.image);

                // Operando izquierdo
                nodoOperacion.agregarHijo(izquierda);

                // Token del operador
                nodoOperacion.agregarHijo(new Arbol("Token: " + op.image));

                        // Operando derecho.
                nodoOperacion.agregarHijo(derecha);

                // Actualizamos (si, otravez) izquierda
                izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// Terminos (*, /, %, &&)
  static final public Arbol termino() throws ParseException {Arbol izquierda, derecha;
        Token op;
    // Primer termino
            izquierda = factor();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_MULTIPLICACION:
      case OPERADOR_DIVISION:
      case OPERADOR_MODULO:
      case OPERADOR_AND:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR_MULTIPLICACION:{
        op = jj_consume_token(OPERADOR_MULTIPLICACION);
        break;
        }
      case OPERADOR_DIVISION:{
        op = jj_consume_token(OPERADOR_DIVISION);
        break;
        }
      case OPERADOR_MODULO:{
        op = jj_consume_token(OPERADOR_MODULO);
        break;
        }
      case OPERADOR_AND:{
        op = jj_consume_token(OPERADOR_AND);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      derecha = factor();
// Nuevo nodo
                Arbol nodoOperacion = new Arbol("Operacion_MUL_DIV_MOD_AND: " + op.image);

                // Acumulamos el mini arbol anterior (la o las rama enteriores).
                nodoOperacion.agregarHijo(izquierda);

                // Token del operador
                nodoOperacion.agregarHijo(new Arbol ("Token: " + op.image));

                // Operando derecho
                nodoOperacion.agregarHijo(derecha);

                // Actualizamos (si, otravez) izquierda
                izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// Factores (!, ++, --)
// Operadores primarios (iden) y unarios 
  static final public Arbol factor() throws ParseException {Arbol nodo;
        Token t;
        Token parA, parC; // Necesario para paréntesis

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_ENTERO:{
      t = jj_consume_token(NUMERO_ENTERO);
{if ("" != null) return new Arbol("Literal_INT: " + t.image);}
      break;
      }
    case NUMERO_FLOTANTE:{
      t = jj_consume_token(NUMERO_FLOTANTE);
{if ("" != null) return new Arbol("Literal_FLOAT: " + t.image);}
      break;
      }
    case CADENA_DE_CARACTERES:{
      t = jj_consume_token(CADENA_DE_CARACTERES);
{if ("" != null) return new Arbol("Literal_CADENA_DE_CARACTERES: " + t.image);}
      break;
      }
    case IDENTIFICADOR:{
      t = jj_consume_token(IDENTIFICADOR);
//return new Arbol("Literal_IDENTIFICADOR: " + t.image);
      Simbolo simboloUsado = tabla.buscar(t.image);
      if (simboloUsado == null)
        {
            // Reportar error si la variable no fue encontrada en ningún ámbito
            System.err.println("Error Semantico ??? [:v] L\u00ednea: " + t.beginLine + " La variable o funci\u00f3n '"
                + t.image + "' no ha sido declarada.");
        }

        {if ("" != null) return new Arbol("Literal_IDENTIFICADOR: " + t.image);}
      break;
      }
    case PARENTESIS_ABRE:{
      parA = jj_consume_token(PARENTESIS_ABRE);
      nodo = expresion();
      parC = jj_consume_token(PARENTESIS_CIERRA);
Arbol nodoAgrupacion = new Arbol("Agrupacion");
       nodoAgrupacion.agregarHijo(new Arbol("Token: " + parA.image));
       nodoAgrupacion.agregarHijo(nodo);

       nodoAgrupacion.agregarHijo(new Arbol("Token: " + parC.image));
       {if ("" != null) return nodoAgrupacion;}
      break;
      }
    case OPERADOR_NOT:{
      t = jj_consume_token(OPERADOR_NOT);
      nodo = factor();
Arbol nodoUnario = new Arbol("Unario_NOT");
       nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
       nodoUnario.agregarHijo(nodo);

       {if ("" != null) return nodoUnario;}
      break;
      }
    case OPERADOR_INCREMENTO:{
      t = jj_consume_token(OPERADOR_INCREMENTO);
      nodo = factor();
Arbol nodoUnario = new Arbol("Unario_INC");
       nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
       nodoUnario.agregarHijo(nodo);

       {if ("" != null) return nodoUnario;}
      break;
      }
    case OPERADOR_DECREMENTO:{
      t = jj_consume_token(OPERADOR_DECREMENTO);
      nodo = factor();
Arbol nodoUnario = new Arbol("Unario_DEC");
       nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
       nodoUnario.agregarHijo(nodo);

       {if ("" != null) return nodoUnario;}
      break;
      }
    case OPERADOR_RESTA:{
      t = jj_consume_token(OPERADOR_RESTA);
      nodo = factor();
Arbol nodoUnario = new Arbol("Unario_RESTA");
       nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
       nodoUnario.agregarHijo(nodo);

       {if ("" != null) return nodoUnario;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Fin de las expresiones
  static final public 
Arbol declaracionDeVariable() throws ParseException {Arbol nodoDeclaracion = new Arbol("DeclaracionDeVariable");
        Token t_decl, t_dos_puntos, t_id, t_pc, t_asig;
        String tipoDato;
        Arbol exp; // Creo que ya existen :v

    t_decl = jj_consume_token(INICIO_DECLARACION_VARIABLE);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_decl.image));
    tipoDato = tiposDeDatos();
nodoDeclaracion.agregarHijo(new Arbol("Tipo: " + tipoDato));
    t_dos_puntos = jj_consume_token(DOS_PUNTOS);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_dos_puntos.image));
    // Token identificador
            t_id = jj_consume_token(IDENTIFICADOR);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_id.image));
                Simbolo nuevoSimbolo = new Simbolo(t_id.image, tipoDato, tabla.getAmbitoActual(), t_id.beginLine);
        tabla.insertar(nuevoSimbolo);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_ASIGNACION:{
      t_asig = jj_consume_token(OPERADOR_ASIGNACION);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
nodoDeclaracion.agregarHijo(exp);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    // - > Solo si hay una asignacion.
    
            t_pc = jj_consume_token(PUNTO_Y_COMA);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoDeclaracion;}
    throw new Error("Missing return statement in function");
}

// print!("Hola mundo");
  static final public Arbol salida() throws ParseException {Arbol nodoSalida = new Arbol("SentenciaDeSalida");
        Arbol exp;
        Token t_salida, t_pa, t_pc, t_pyc;
    t_salida = jj_consume_token(SALIDA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_salida.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pa.image));
    exp = expresion();
nodoSalida.agregarHijo(exp);
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_pyc = jj_consume_token(PUNTO_Y_COMA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pyc.image));
{if ("" != null) return nodoSalida;}
    throw new Error("Missing return statement in function");
}

// scan!(operando);
  static final public Arbol entrada() throws ParseException {Arbol nodoEntrada = new Arbol("SentenciaDeEntrada");
        Token t_entrada, t_pa, t_id, t_pc, t_pyc;
    t_entrada = jj_consume_token(ENTRADA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_entrada.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pa.image));
    t_id = jj_consume_token(IDENTIFICADOR);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_id.image));
          Simbolo simboloEntrada = tabla.buscar(t_id.image);
        if (simboloEntrada == null)
        {
            System.err.println("Error ??? L\u00ednea: " + t_id.beginLine + ": La variable '" + t_id.image + "' para entrada no ha sido declarada.");
        }
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_pyc = jj_consume_token(PUNTO_Y_COMA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pyc.image));
{if ("" != null) return nodoEntrada;}
    throw new Error("Missing return statement in function");
}

// Vector
  static final public Arbol declaracionVector() throws ParseException {Arbol nodoDeclaracionVector = new Arbol("Declarcion_VECTOR");
        String tipoDato;
        Arbol dimensionVector;
        Token t_id, t_pc;
    tipoDato = tiposDeDatos();
nodoDeclaracionVector.agregarHijo(new Arbol("Tipo: " + tipoDato));
    t_id = jj_consume_token(IDENTIFICADOR);
nodoDeclaracionVector.agregarHijo(new Arbol("ID_Vector: " + t_id.image));
                Simbolo nuevoVector = new Simbolo(t_id.image, "vector", tabla.getAmbitoActual(), t_id.beginLine);
        tabla.insertar(nuevoVector);
    dimensionVector = dimensionVector();
nodoDeclaracionVector.agregarHijo(dimensionVector);
    t_pc = jj_consume_token(PUNTO_Y_COMA);
nodoDeclaracionVector.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoDeclaracionVector;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol dimensionVector() throws ParseException {Arbol nodoDimensionVector = new Arbol("Dimension_Del_Vector");
        Token t_ca, t_int, t_id, t_cc;
    t_ca = jj_consume_token(CORCHETE_ABRE);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_ca.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_ENTERO:{
      t_int = jj_consume_token(NUMERO_ENTERO);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_int.image));
      break;
      }
    case IDENTIFICADOR:{
      t_id = jj_consume_token(IDENTIFICADOR);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_id.image));
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t_cc = jj_consume_token(CORCHETE_CIERRA);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_cc.image));
{if ("" != null) return nodoDimensionVector;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol accesoVector() throws ParseException {Arbol nodoAccesoVec = new Arbol("AccesoAlVEctor");
        Token t_id, t_ca, t_int, t_cc;
    t_id = jj_consume_token(IDENTIFICADOR);
nodoAccesoVec.agregarHijo(new Arbol("ID_Vector: " + t_id.image));
                Simbolo simboloVector = tabla.buscar(t_id.image);

        if (simboloVector == null)
        {
            System.err.println("Error ??? L\u00ednea: " + t_id.beginLine + ": El vector '" + t_id.image + "' no ha sido declarado.");
        }
        else if (!"vector".equals(simboloVector.tipo))
        {
            System.err.println("Error ??? L\u00ednea: " + t_id.beginLine + ": El identificador '" + t_id.image + "' no es un vector.");
        }
    t_ca = jj_consume_token(CORCHETE_ABRE);
nodoAccesoVec.agregarHijo(new Arbol("Token: " + t_ca.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_ENTERO:{
      t_int = jj_consume_token(NUMERO_ENTERO);
nodoAccesoVec.agregarHijo(new Arbol("Literal_INT_Indice: " + t_int.image));
      break;
      }
    case IDENTIFICADOR:{
      t_id = jj_consume_token(IDENTIFICADOR);
nodoAccesoVec.agregarHijo(new Arbol("ID_Indice: " + t_id.image));

              Simbolo simboloIndice = tabla.buscar(t_id.image);
              if (simboloIndice == null)
              {
                  System.err.println("Error ??? L\u00ednea: " + t_id.beginLine + ": La variable para el \u00edndice '"
                        + t_id.image + "' no ha sido declarada.");
              }
              else if (!"int".equals(simboloIndice.tipo))
              {
                  System.err.println("Error ??? L\u00ednea: " + t_id.beginLine
                        + ": El \u00edndice del vector debe ser de tipo entero, pero se encontr\u00f3 '" + simboloIndice.tipo + "'.");
              }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t_cc = jj_consume_token(CORCHETE_CIERRA);
nodoAccesoVec.agregarHijo(new Arbol("Token: " + t_cc.image));
{if ("" != null) return nodoAccesoVec;}
    throw new Error("Missing return statement in function");
}

// - > FIN vector


// Bucles.
// - > For
  static final public Arbol bucleFor() throws ParseException {Arbol nodoBucleFor = new Arbol("Bucle_FOR");
        Arbol inicializacion, condicion, actualizacion, bloque;
        Token t_for, t_pa, t_pc, t_pyc1, t_pyc2;
    t_for = jj_consume_token(BUCLE_FOR);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_for.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pa.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INICIO_DECLARACION_VARIABLE:
    case IDENTIFICADOR:{
      inicializacion = inicializacionFor();
nodoBucleFor.agregarHijo(inicializacion);
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    t_pyc1 = jj_consume_token(PUNTO_Y_COMA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pyc1.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPERADOR_RESTA:
    case OPERADOR_INCREMENTO:
    case OPERADOR_DECREMENTO:
    case OPERADOR_NOT:
    case PARENTESIS_ABRE:
    case NUMERO_FLOTANTE:
    case NUMERO_ENTERO:
    case IDENTIFICADOR:
    case CADENA_DE_CARACTERES:{
      condicion = expresion();
nodoBucleFor.agregarHijo(condicion);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
    t_pyc2 = jj_consume_token(PUNTO_Y_COMA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pyc2.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      actualizacion = actualizacionFor();
nodoBucleFor.agregarHijo(actualizacion);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pc.image));
    bloque = bloqueDeCodigo();
nodoBucleFor.agregarHijo(bloque);
{if ("" != null) return nodoBucleFor;}
    throw new Error("Missing return statement in function");
}

// Declaracion e inicializacion de variables en bucles.
  static final public Arbol inicializacionFor() throws ParseException {Arbol nodoIniFor = new Arbol("Inicializacion_Bucle_FOR");
        Arbol declVar, asigVar;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INICIO_DECLARACION_VARIABLE:{
      declVar = declaracionDeVariable();
nodoIniFor.agregarHijo(declVar);
                {if ("" != null) return nodoIniFor;}
      break;
      }
    case IDENTIFICADOR:{
      asigVar = asignacionSinPuntoYComa();
nodoIniFor.agregarHijo(asigVar);
            {if ("" != null) return nodoIniFor;}
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Auxiliar
  static final public Arbol asignacionSinPuntoYComa() throws ParseException {Arbol nodoAsignacion = new Arbol("AsignacionSinPuntoYComa");
    Arbol accVector, exp;
    Token t_id, t_asig;
    if (jj_2_3(3)) {
      t_id = jj_consume_token(IDENTIFICADOR);
nodoAsignacion.agregarHijo(new Arbol("ID_Asignacion: " + t_id.image));
      t_asig = jj_consume_token(OPERADOR_ASIGNACION);
nodoAsignacion.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
nodoAsignacion.agregarHijo(exp);
{if ("" != null) return nodoAsignacion;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFICADOR:{
        accVector = accesoVector();
nodoAsignacion.agregarHijo(accVector);
        t_asig = jj_consume_token(OPERADOR_ASIGNACION);
nodoAsignacion.agregarHijo(new Arbol("Token: " + t_asig.image));
        exp = expresion();
nodoAsignacion.agregarHijo(exp);
{if ("" != null) return nodoAsignacion;}
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Arbol actualizacionFor() throws ParseException {Arbol nodoActualizacion = new Arbol("Actualizacion_Bucle_FOR");
   Arbol asig;
   Token t_coma;
    // asignaxino.
        asig = asignacionSinPuntoYComa();
nodoActualizacion.agregarHijo(asig);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_9;
      }
      t_coma = jj_consume_token(COMA);
nodoActualizacion.agregarHijo(new Arbol("Token: " + t_coma.image));
      asig = asignacionSinPuntoYComa();
nodoActualizacion.agregarHijo(asig);
    }
{if ("" != null) return nodoActualizacion;}
    throw new Error("Missing return statement in function");
}

// - > While
  static final public Arbol bucleWhile() throws ParseException {Arbol nodoBucleWhile = new Arbol("Bucle_WHILE");

    Arbol condicion, bloque;
    Token t_while, t_pa, t_pc;
    t_while = jj_consume_token(BUCLE_WHILE);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_while.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_pa.image));
    condicion = expresion();
nodoBucleWhile.agregarHijo(condicion);
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_pc.image));
    bloque = bloqueDeCodigo();
nodoBucleWhile.agregarHijo(bloque);
{if ("" != null) return nodoBucleWhile;}
    throw new Error("Missing return statement in function");
}

// FIN bucles.


// Condicionales.
// - > If
  static final public Arbol condicionalIf() throws ParseException {Arbol nodoIf = new Arbol("Condicional_IF");

    Arbol condicion, bloqueIf, bloqueElse;
    Token t_if, t_pa, t_pc, t_else;
    // "if"
        t_if = jj_consume_token(CONDICIONAL_IF);
nodoIf.agregarHijo(new Arbol("Token: " + t_if.image));
    // "("
        t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoIf.agregarHijo(new Arbol("Token: " + t_pa.image));
    // Condición.
        condicion = expresion();
nodoIf.agregarHijo(condicion);
    // ")"
        t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoIf.agregarHijo(new Arbol("Token: " + t_pc.image));
    // Codigo que ejecuta el if.
        bloqueIf = bloqueDeCodigo();
nodoIf.agregarHijo(bloqueIf);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CONDICIONAL_ELSE:{
      // else
              t_else = jj_consume_token(CONDICIONAL_ELSE);
nodoIf.agregarHijo(new Arbol("Token: " + t_else.image));
nodoIf.agregarHijo(new Arbol("Bloque_ELSE"));
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LLAVE_ABRE:{
        // ELSE { bloqueDeCodigo() }
                    bloqueElse = bloqueDeCodigo();
nodoIf.agregarHijo(bloqueElse);
        break;
        }
      case CONDICIONAL_IF:{
        bloqueElse = condicionalIf();
nodoIf.agregarHijo(bloqueElse);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
{if ("" != null) return nodoIf;}
    throw new Error("Missing return statement in function");
}

// - > Swich
  static final public Arbol condicionalSwitch() throws ParseException {Arbol nodoSwitch = new Arbol("Condicional_SWITCH");
    Arbol expresionControl, caso, defecto;
    Token t_switch, t_pa, t_pc, t_lla, t_llc;
    t_switch = jj_consume_token(CONDICIONAL_SWITCH);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_switch.image));
    t_pa = jj_consume_token(PARENTESIS_ABRE);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_pa.image));
    expresionControl = expresion();
nodoSwitch.agregarHijo(expresionControl);
    t_pc = jj_consume_token(PARENTESIS_CIERRA);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_lla = jj_consume_token(LLAVE_ABRE);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_lla.image));
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE_CONDICIONAL_SWITCH:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_10;
      }
      caso = caseSwitch();
nodoSwitch.agregarHijo(caso);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULT_SWITCH:{
      defecto = defaultSwitch();
nodoSwitch.agregarHijo(defecto);
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    t_llc = jj_consume_token(LLAVE_CIERRA);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_llc.image));
{if ("" != null) return nodoSwitch;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol caseSwitch() throws ParseException {Arbol nodoCase = new Arbol("Case_SWITCH");
    Arbol sentencia, breakSentencia;
    Token t_case, t_valor, t_dospuntos;
    // CASE_CONDICIONAL_SWITCH ("case")
        t_case = jj_consume_token(CASE_CONDICIONAL_SWITCH);
nodoCase.agregarHijo(new Arbol("Token: " + t_case.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO_ENTERO:{
      t_valor = jj_consume_token(NUMERO_ENTERO);
nodoCase.agregarHijo(new Arbol("Valor_Case_INT: " + t_valor.image));
      break;
      }
    case CADENA_DE_CARACTERES:{
      t_valor = jj_consume_token(CADENA_DE_CARACTERES);
nodoCase.agregarHijo(new Arbol("Valor_Case_STRING: " + t_valor.image));
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t_dospuntos = jj_consume_token(DOS_PUNTOS);
nodoCase.agregarHijo(new Arbol("Token: " + t_dospuntos.image));
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case CONDICIONAL_IF:
      case CONDICIONAL_SWITCH:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case INICIO_DECLARACION_VARIABLE:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_11;
      }
      sentencia = sentencia();
nodoCase.agregarHijo(sentencia);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      breakSentencia = sentenciaBreak();
nodoCase.agregarHijo(breakSentencia);
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
{if ("" != null) return nodoCase;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol sentenciaBreak() throws ParseException {Arbol nodoStmtBreak = new Arbol("SentenciaBreak");
        Token t_break, t_pc;
    t_break = jj_consume_token(BREAK);
nodoStmtBreak.agregarHijo(new Arbol("Token: " + t_break.image));
    t_pc = jj_consume_token(PUNTO_Y_COMA);
nodoStmtBreak.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoStmtBreak;}
    throw new Error("Missing return statement in function");
}

  static final public Arbol defaultSwitch() throws ParseException {Arbol nodoDefault = new Arbol("Default_SWITCH");
    Arbol sentencia, breakSentencia;
    Token t_default, t_dospuntos;
    t_default = jj_consume_token(DEFAULT_SWITCH);
nodoDefault.agregarHijo(new Arbol("Token: " + t_default.image));
    t_dospuntos = jj_consume_token(DOS_PUNTOS);
nodoDefault.agregarHijo(new Arbol("Token: " + t_dospuntos.image));
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case CONDICIONAL_IF:
      case CONDICIONAL_SWITCH:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case INICIO_DECLARACION_VARIABLE:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_12;
      }
      sentencia = sentencia();
nodoDefault.agregarHijo(sentencia);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      breakSentencia = sentenciaBreak();
nodoDefault.agregarHijo(breakSentencia);
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
{if ("" != null) return nodoDefault;}
    throw new Error("Missing return statement in function");
}

// FIN condicionales.
  static final public 
String tiposDeDatos() throws ParseException {//Arbol nodoTipo = new Arbol("TipoDeDato");
        Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:{
      t = jj_consume_token(ENTERO);
{if ("" != null) return t.image;}
      break;
      }
    case FLOTANTE:{
      t = jj_consume_token(FLOTANTE);
{if ("" != null) return t.image;}
      break;
      }
    case BOOLEANO:{
      t = jj_consume_token(BOOLEANO);
{if ("" != null) return t.image;}
      break;
      }
    case CHAR:{
      t = jj_consume_token(CHAR);
{if ("" != null) return t.image;}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return t.image;}
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_3R_accesoVector_836_9_14()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_accesoVector_856_19_17()) {
    jj_scanpos = xsp;
    if (jj_3R_accesoVector_859_19_18()) return true;
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_llamadaFuncion_448_9_13()) return true;
    return false;
  }

  static private boolean jj_3R_factor_603_5_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_factor_603_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_606_5_23()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_609_5_24()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_612_5_25()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_628_5_26()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_639_5_27()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_648_5_28()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_657_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_666_5_30()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_factor_603_5_22()
 {
    if (jj_scan_token(NUMERO_ENTERO)) return true;
    return false;
  }

  static private boolean jj_3R_factor_648_5_28()
 {
    if (jj_scan_token(OPERADOR_INCREMENTO)) return true;
    return false;
  }

  static private boolean jj_3R_llamadaFuncion_448_9_13()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PARENTESIS_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_llamadaFuncion_455_17_16()) jj_scanpos = xsp;
    if (jj_scan_token(PARENTESIS_CIERRA)) return true;
    return false;
  }

  static private boolean jj_3R_factor_639_5_27()
 {
    if (jj_scan_token(OPERADOR_NOT)) return true;
    return false;
  }

  static private boolean jj_3R_accesoVector_859_19_18()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_accesoVector_856_19_17()
 {
    if (jj_scan_token(NUMERO_ENTERO)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(OPERADOR_ASIGNACION)) return true;
    if (jj_3R_expresion_484_9_15()) return true;
    return false;
  }

  static private boolean jj_3R_expresion_484_9_15()
 {
    if (jj_3R_expresionRelacional_522_9_19()) return true;
    return false;
  }

  static private boolean jj_3R_factor_628_5_26()
 {
    if (jj_scan_token(PARENTESIS_ABRE)) return true;
    return false;
  }

  static private boolean jj_3R_expresionRelacional_522_9_19()
 {
    if (jj_3R_termino_564_9_20()) return true;
    return false;
  }

  static private boolean jj_3R_factor_666_5_30()
 {
    if (jj_scan_token(OPERADOR_RESTA)) return true;
    return false;
  }

  static private boolean jj_3R_termino_564_9_20()
 {
    if (jj_3R_factor_603_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_factor_612_5_25()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_accesoVector_836_9_14()) return true;
    return false;
  }

  static private boolean jj_3R_factor_657_5_29()
 {
    if (jj_scan_token(OPERADOR_DECREMENTO)) return true;
    return false;
  }

  static private boolean jj_3R_factor_609_5_24()
 {
    if (jj_scan_token(CADENA_DE_CARACTERES)) return true;
    return false;
  }

  static private boolean jj_3R_llamadaFuncion_455_17_16()
 {
    if (jj_3R_expresion_484_9_15()) return true;
    return false;
  }

  static private boolean jj_3R_factor_606_5_23()
 {
    if (jj_scan_token(NUMERO_FLOTANTE)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public GramaticaTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[35];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x7c0,0x800,0x7c0,0x7c0,0x7c0,0x0,0x800,0x98400000,0x40600000,0x40600000,0x1f8000,0x1f8000,0x23800000,0x23800000,0x98400000,0x4000000,0x0,0x0,0x0,0x98400000,0x0,0x0,0x0,0x800,0x0,0x0,0x0,0x0,0x0,0x7c0,0x0,0x7c0,0x0,0x7c0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x20000,0x9d00c5,0x0,0x0,0x9d00c5,0x9d00c5,0x800000,0x0,0x1e00100,0x0,0x0,0x0,0x0,0x0,0x0,0x1e00100,0x0,0xc00000,0xc00000,0x810000,0x1e00100,0x800000,0x810000,0x800000,0x0,0x401,0x2,0x8,0x10,0x1400000,0x9d00c5,0x20,0x9d00c5,0x20,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[3];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Gramatica(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Gramatica(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Gramatica(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GramaticaTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GramaticaTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Gramatica(GramaticaTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[57];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 35; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 57; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 3; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
